version: "3"
services:
  mysql_container_service:
    container_name: mysql_container
    hostname: mysql_host
    image: mysql:8
#   image: postgres:15
#   restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "asac"
      MYSQL_PASSWORD: "1234"
      MYSQL_DATABASE: "example"
#     POSTGRES_USER: "asac"
#     POSTGRES_PASSWORD: "1234"
#     POSTGRES_DB: "example"
    ports:
      - 4000:3306
#     - 6000:5432

  spring_container_service:
    container_name: spring_container
    build: .
    ports:
      - 1000:8080
    environment:
      SPRING_PROFILE: develop
    depends_on:
      - mysql_container_service